// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetDnsConfigResponse = { dns: LandscapeDnsConfig; hash: string };

export type GetMetricConfigResponse = {
  metric: LandscapeMetricConfig;
  hash: string;
};

export type GetUIConfigResponse = { ui: LandscapeUIConfig; hash: string };

/**
 * auth realte config
 */
export type LandscapeAuthConfig = {
  /**
   * login user
   */
  admin_user: string | null;
  /**
   * login pass
   */
  admin_pass: string | null;
};

/**
 * Read & Write <CONFIG_PATH>/landscape.toml
 */
export type LandscapeConfig = {
  auth: LandscapeAuthConfig;
  web: LandscapeWebConfig;
  log: LandscapeLogConfig;
  store: LandscapeStoreConfig;
  metric: LandscapeMetricConfig;
  dns: LandscapeDnsConfig;
  ui: LandscapeUIConfig;
};

export type LandscapeDnsConfig = {
  cache_capacity?: number;
  cache_ttl?: number;
  negative_cache_ttl?: number;
};

export type LandscapeLogConfig = {
  log_path: string | null;
  debug: boolean | null;
  log_output_in_terminal: boolean | null;
  max_log_files: number | null;
};

export type LandscapeMetricConfig = {
  conn_retention_mins?: bigint;
  conn_retention_minute_days?: bigint;
  conn_retention_hour_days?: bigint;
  conn_retention_day_days?: bigint;
  dns_retention_days?: bigint;
  batch_size?: number;
  flush_interval_secs?: bigint;
  max_memory?: number;
  max_threads?: number;
};

export type LandscapeStoreConfig = { database_path: string | null };

export type LandscapeUIConfig = {
  language?: string;
  timezone?: string;
  theme?: string;
};

/**
 * web realte config
 */
export type LandscapeWebConfig = {
  /**
   * Web Root
   */
  web_root: string | null;
  /**
   * Listen HTTP port
   */
  port: number | null;
  /**
   * Listen HTTPS port
   */
  https_port: number | null;
  /**
   * Listen address
   */
  address: string | null;
};

export type UpdateDnsConfigRequest = {
  new_dns: LandscapeDnsConfig;
  expected_hash: string;
};

export type UpdateMetricConfigRequest = {
  new_metric: LandscapeMetricConfig;
  expected_hash: string;
};

export type UpdateUIConfigRequest = {
  new_ui: LandscapeUIConfig;
  expected_hash: string;
};
