// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "./network.d";

export type IPV6PDConfig = { mac: MacAddr };

export type IPV6PDServiceConfig = {
  iface_name: string;
  enable: boolean;
  config: IPV6PDConfig;
  update_at: number;
};
