// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "./network.d";

export type ArpScanInfo = { infos: Array<ArpScanInfoItem> };

export type ArpScanInfoItem = { ip: string; mac: MacAddr };

export type DHCPv4OfferInfo = {
  boot_time: number;
  relative_boot_time: number;
  offered_ips: Array<DHCPv4OfferInfoItem>;
};

export type DHCPv4OfferInfoItem = {
  hostname: string | null;
  mac: MacAddr;
  ip: string;
  relative_active_time: number;
  expire_time: number;
  is_static: boolean;
};

/**
 * DHCP Server IPv4 Config
 */
export type DHCPv4ServerConfig = {
  /**
   * dhcp options
   * range start
   */
  ip_range_start: string;
  /**
   * range end [not include]
   */
  ip_range_end: string | null;
  /**
   * DHCP Server Addr e.g. 192.168.1.1
   */
  server_ip_addr: string;
  /**
   * network mask e.g. 255.255.255.0 = 24
   */
  network_mask: number;
  address_lease_time: number | null;
  /**
   * Static MAC --> IP address binding
   */
  mac_binding_records: Array<MacBindingRecord>;
};

export type DHCPv4ServiceConfig = {
  iface_name: string;
  enable: boolean;
  config: DHCPv4ServerConfig;
  /**
   * 最近一次编译时间
   */
  update_at: number;
};

export type MacBindingRecord = {
  mac: MacAddr;
  ip: string;
  expire_time: number;
};
