// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "./network.d";

export type ArpScanInfo = { infos: Array<ArpScanInfoItem> };

export type ArpScanInfoItem = { ip: string; mac: MacAddr };

export type DHCPv4OfferInfo = {
  boot_time: number;
  relative_boot_time: number;
  offered_ips: Array<DHCPv4OfferInfoItem>;
};

export type DHCPv4OfferInfoItem = {
  hostname: string | null;
  mac: MacAddr;
  ip: string;
  relative_active_time: number;
  expire_time: number;
  is_static: boolean;
};
