// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowMark } from "../flow.d";
import type { GeoConfigKey } from "./geo.d";

/**
 * DNS 配置
 */
export type DNSRuleConfig = {
  id?: string;
  /**
   * 名称
   */
  name: string;
  /**
   * 优先级
   */
  index: number;
  /**
   * 是否启用
   */
  enable: boolean;
  /**
   * 过滤模式
   */
  filter: FilterResult;
  /**
   * 上游配置 ID
   */
  upstream_id: string;
  /**
   * 源 IP 绑定配置
   */
  bind_config: DnsBindConfig;
  /**
   * 流量标记
   */
  mark: FlowMark;
  /**
   * 匹配规则列表
   */
  source: Array<RuleSource>;
  /**
   * 关联 Flow ID
   */
  flow_id: number;
  /**
   * 最近一次更新时间
   */
  update_at?: number;
};

export type DnsBindConfig = {
  /**
   * 绑定地址 v4 (可选)
   */
  bind_addr4?: string;
  /**
   * 绑定地址 v6 (可选)
   */
  bind_addr6?: string;
};

export type DnsUpstreamConfig = {
  id?: string;
  remark: string;
  mode: DnsUpstreamMode;
  ips: Array<string>;
  port: number | null;
  enable_ip_validation: boolean | null;
  update_at?: number;
};

export type DnsUpstreamMode =
  | { "t": "plaintext" }
  | { "t": "tls"; domain: string }
  | { "t": "https"; domain: string; http_endpoint: string | null }
  | { "t": "quic"; domain: string };

export type DomainConfig = { match_type: DomainMatchType; value: string };

export type DomainMatchType = "plain" | "regex" | "domain" | "full";

export type FilterResult = "unfilter" | "only_ipv4" | "only_ipv6";

export type RuleSource =
  | { "t": "geo_key" } & GeoConfigKey
  | { "t": "config" } & DomainConfig;
