// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandscapeDnsRecordType } from "./dns_record_type.d";

export type CheckChainDnsResult = {
  redirect_id: string | null;
  rule_id: string | null;
  records: Array<LandscapeRecord> | null;
  cache_records: Array<LandscapeRecord> | null;
};

export type CheckDnsReq = {
  flow_id: number;
  domain: string;
  record_type: LandscapeDnsRecordType;
};

export type CheckDnsResult = {
  config: any | null;
  records: Array<LandscapeRecord> | null;
  cache_records: Array<LandscapeRecord> | null;
};

export type LandscapeRecord = {
  name: string;
  rr_type: string;
  ttl: number;
  data: string;
};
