// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "./network.d";

export type EnrolledDevice = {
  id?: string;
  update_at?: number;
  /**
   * Optional interface name this binding belongs to
   */
  iface_name?: string;
  /**
   * The display name chosen by the user
   */
  name: string;
  /**
   * Name to show when "Private Mode" is enabled
   */
  fake_name?: string;
  /**
   * Optional remark for the device
   */
  remark?: string;
  /**
   * Unique MacAddr for this binding
   */
  mac: MacAddr;
  /**
   * Static IPv4 assignment (Optional)
   */
  ipv4?: string;
  /**
   * Static IPv6 assignment (Optional)
   */
  ipv6?: string;
  /**
   * Tags for grouping devices (e.g., "Family", "IoT")
   */
  tag: Array<string>;
};

export type ValidateIpPayload = { iface_name: string; ipv4: string };
