// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpConfig } from "../flow";
import type { GeoConfigKey } from "./geo.d";

export type FirewallBlacklistConfig = {
  id?: string;
  enable: boolean;
  source: Array<FirewallBlacklistSource>;
  remark: string;
  update_at?: number;
};

export type FirewallBlacklistSource =
  | { "t": "geo_key" } & GeoConfigKey
  | { "t": "config" } & IpConfig;
