// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowMark } from "./flow.d";

export type FirewallRuleConfig = {
  id: string | null;
  index: number;
  enable: boolean;
  remark: string;
  items: Array<FirewallRuleConfigItem>;
  /**
   * 流量标记
   */
  mark: FlowMark;
  update_at: number;
};

/**
 * 配置的小项
 */
export type FirewallRuleConfigItem = {
  ip_protocol: LandscapeIpProtocolCode | null;
  local_port: string | null;
  address: string;
  ip_prefixlen: number;
};

export type FirewallServiceConfig = {
  iface_name: string;
  enable: boolean;
  update_at: number;
};

export type LandscapeIpProtocolCode = "tcp" | "udp" | "icmp" | "icmpv6";
