// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FlowMark = {
  /**
   * Action
   */
  action: FlowMarkAction;
  /**
   * 允许 NAT 端口共享
   */
  allow_reuse_port: boolean;
  /**
   * Flow Id
   */
  flow_id: number;
};

export type FlowMarkAction = { "t": "keep_going" } | { "t": "direct" } | {
  "t": "drop";
} | { "t": "redirect" };

/**
 * 可移除
 */
export type FlowWanServiceConfig = {
  iface_name: string;
  enable: boolean;
  update_at: number;
};
