// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoConfigKey } from "./geo.d";
import type { MacAddr } from "./network.d";

/**
 * 流控配置结构体
 */
export type FlowConfig = {
  id?: string;
  /**
   * 是否启用
   */
  enable: boolean;
  /**
   * 流 ID
   */
  flow_id: number;
  /**
   * 匹配规则
   */
  flow_match_rules: Array<FlowEntryRule>;
  /**
   * 处理流量目标网卡, 目前只取第一个
   * 暂定, 可能会移动到具体的网卡上进行设置
   */
  flow_targets: Array<FlowTarget>;
  /**
   * 备注
   */
  remark: string;
  update_at?: number;
};

export type FlowEntryMatchMode = { "t": "mac"; mac_addr: MacAddr } | {
  "t": "ip";
  ip: string;
  prefix_len: number;
};

/**
 * Flow 入口匹配规则
 */
export type FlowEntryRule = { qos: number | null; mode: FlowEntryMatchMode };

export type FlowMark = {
  /**
   * Action
   */
  action: FlowMarkAction;
  /**
   * 允许 NAT 端口共享
   */
  allow_reuse_port: boolean;
  /**
   * Flow Id
   */
  flow_id: number;
};

export type FlowMarkAction = { "t": "keep_going" } | { "t": "direct" } | {
  "t": "drop";
} | { "t": "redirect" };

export type FlowTarget = { "t": "interface"; name: string } | {
  "t": "netns";
  container_name: string;
};

/**
 * 可移除
 */
export type FlowWanServiceConfig = {
  iface_name: string;
  enable: boolean;
  update_at: number;
};

export type IpConfig = { ip: string; prefix: number };

export type WanIPRuleSource =
  | { "t": "geo_key" } & GeoConfigKey
  | { "t": "config" } & IpConfig;

/**
 * 对于外部 IP 规则
 */
export type WanIpRuleConfig = {
  id: string | null;
  index: number;
  enable: boolean;
  /**
   * 流量标记
   */
  mark: FlowMark;
  /**
   * 匹配规则列表
   */
  source: Array<WanIPRuleSource>;
  remark: string;
  flow_id: number;
  override_dns: boolean;
  update_at: number;
};
