// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainMatchType } from "./dns.d";

/**
 * 存储在 file cache 中
 */
export type GeoDomainConfig = {
  name: string;
  key: string;
  values: Array<GeoSiteFileConfig>;
};

export type GeoSiteDirectItem = {
  key: string;
  values: Array<GeoSiteFileConfig>;
};

export type GeoSiteFileConfig = {
  match_type: DomainMatchType;
  value: string;
  attributes: Array<string>;
};

export type GeoSiteSource = {
  "t": "url";
  url: string;
  next_update_at: number;
  geo_keys: Array<string>;
} | { "t": "direct"; data: Array<GeoSiteDirectItem> };

export type GeoSiteSourceConfig = {
  /**
   * 用这个 ID 作为文件名称
   */
  id: string | null;
  /**
   * 记录更新时间
   */
  update_at: number;
  /**
   * 展示名称
   */
  name: string;
  /**
   * 启用状态
   */
  enable: boolean;
  /**
   * 来源配置
   */
  source: GeoSiteSource;
};

export type QueryGeoDomainConfig = { name: string | null };
