// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpConfig } from "../flow.d";

export type GeoIpConfig = {
  name: string;
  key: string;
  values: Array<IpConfig>;
};

export type GeoIpDirectItem = { key: string; values: Array<IpConfig> };

export type GeoIpSource =
  | { "t": "url"; url: string; next_update_at: number }
  | { "t": "direct"; data: Array<GeoIpDirectItem> };

/**
 * Geo IP
 */
export type GeoIpSourceConfig = {
  /**
   * 用这个 ID 作为文件名称
   */
  id: string | null;
  /**
   * 记录更新时间
   */
  update_at: number;
  /**
   * 展示名称
   */
  name: string;
  /**
   * 启用状态
   */
  enable: boolean;
  /**
   * 来源配置
   */
  source: GeoIpSource;
};

export type QueryGeoIpConfig = { name: string | null };
