// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MacAddr } from "../network.d";

export type IPv6NAInfo = { boot_time: number; offered_ips: number };

export type IPv6NAInfoItem = {
  mac: MacAddr;
  ip: string;
  /**
   * Relative to the start time of RA
   */
  relative_active_time: number;
};
