// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowMark } from "../flow.d";
import type { MacAddr } from "../network.d";

export type FlowMatchRequest = {
  src_ipv4?: string;
  src_ipv6?: string;
  src_mac: MacAddr | null;
};

export type FlowMatchResult = {
  flow_id_by_mac: number | null;
  flow_id_by_ip: number | null;
  effective_flow_id: number;
};

export type FlowRuleMatchResult = { mark: FlowMark; priority: number };

export type FlowVerdictRequest = {
  flow_id: number;
  src_ipv4?: string;
  src_ipv6?: string;
  dst_ips: Array<string>;
};

export type FlowVerdictResult = { verdicts: Array<SingleVerdictResult> };

export type SingleVerdictResult = {
  dst_ip: string;
  ip_rule_match: FlowRuleMatchResult | null;
  dns_rule_match: FlowRuleMatchResult | null;
  effective_mark: FlowMark;
  has_cache: boolean;
  cached_mark: number | null;
  cache_consistent: boolean;
};
