// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IfaceIpModelConfig = { "t": "nothing" } | {
  "t": "static";
  default_router_ip: string | null;
  default_router: boolean;
  ipv4: string | null;
  ipv4_mask: number;
  ipv6: string | null;
} | {
  "t": "pppoe";
  default_router: boolean;
  username: string;
  password: string;
  mtu: number;
} | {
  "t": "dhcpclient";
  default_router: boolean;
  hostname: string | null;
  /**
   * Custome Options
   */
  custome_opts: Array<any>;
};
