// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkIfaceConfig } from "./common/iface.d";
import type { MacAddr } from "./network.d";

export type DevState =
  | { "t": "unknown" }
  | { "t": "notpresent" }
  | { "t": "down" }
  | { "t": "lowerlayerdown" }
  | { "t": "testing" }
  | { "t": "dormant" }
  | { "t": "up" }
  | { "t": "other"; "c": number };

/**
 * 设备类型小类
 */
export type DeviceKind =
  | "dummy"
  | "ifb"
  | "bridge"
  | "tun"
  | "nlmon"
  | "vlan"
  | "veth"
  | "vxlan"
  | "bond"
  | "ipvlan"
  | "macvlan"
  | "macvtap"
  | "gretap"
  | "gretap6"
  | "iptun"
  | "sittun"
  | "gretun"
  | "gretun6"
  | "vti"
  | "vrf"
  | "gtp"
  | "ipoib"
  | "wireguard"
  | "xfrm"
  | "macsec"
  | "hsr"
  | { "other": string }
  | "unknow";

/**
 * 设备类型大类
 */
export type DeviceType =
  | "unsupport"
  | "loopback"
  | "ethernet"
  | "ppp"
  | "tunnel"
  | "tunnel6";

/**
 * 已管理的网卡
 */
export type IfaceInfo = {
  /**
   * 持久化的配置
   */
  config: NetworkIfaceConfig;
  /**
   * 当前网卡的配置, 可能网卡现在不存在
   */
  status: LandscapeInterface | null;
  wifi_info: LandscapeWifiInterface | null;
};

export type IfacesInfo = {
  managed: Array<IfaceInfo>;
  unmanaged: Array<RawIfaceInfo>;
};

/**
 * 当前硬件状态结构体
 */
export type LandscapeInterface = {
  iface_name: string;
  index: number;
  mac: MacAddr | null;
  perm_mac: MacAddr | null;
  dev_type: DeviceType;
  dev_kind: DeviceKind;
  dev_status: DevState;
  controller_id: number | null;
  carrier: boolean;
  netns_id: number | null;
  peer_link_id: number | null;
  is_wireless: boolean;
};

/**
 * 当前硬件状态结构体
 */
export type LandscapeWifiInterface = {
  name: string;
  index: number;
  wifi_type: WLANType;
};

/**
 * 未纳入配置的网卡
 */
export type RawIfaceInfo = {
  /**
   * 当前网卡的配置
   */
  status: LandscapeInterface;
  wifi_info: LandscapeWifiInterface | null;
};

/**
 * 无线接口类型
 */
export type WLANType =
  | { "t": "Unspecified" }
  | { "t": "Adhoc" }
  | { "t": "Station" }
  | { "t": "Ap" }
  | { "t": "ApVlan" }
  | { "t": "Wds" }
  | { "t": "Monitor" }
  | { "t": "MeshPoint" }
  | { "t": "P2pClient" }
  | { "t": "P2pGo" }
  | { "t": "P2pDevice" }
  | { "t": "Ocb" }
  | { "t": "Nan" }
  | { "t": "Other" } & number;
